# .github/workflows/frontend-tests.yml

name: ESV Frontend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-frontend-tests:
    name: Run frontend tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: esv_app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false